import { UserBankAccount } from '@bintang-bank/entities';

export const UserAccountList: UserBankAccount = {
  accounts: [
    {
      id: 1,
      userId: 'b5yMZwbnYAQ0Z2AzSXntYN9XZWk1',
      bankName: 'Bintang Bank',
      accountNumber: '1234567890',
      accountName: 'Personal Savings',
      accountType: 'Savings',
      amount: '5,000,00',
      isDormant: false,
      createdAt: new Date(),
    },
    {
      id: 2,
      userId: 'b5yMZwbnYAQ0Z2AzSXntYN9XZWk1',
      bankName: 'Bintang Bank',
      accountNumber: '0987654321',
      accountName: 'Fixed Deposit-i',
      accountType: 'Current',
      amount: '10,000,00',
      isDormant: false,
      createdAt: new Date(),
    },
    {
      id: 3,
      userId: 'b5yMZwbnYAQ0Z2AzSXntYN9XZWk1',
      bankName: 'Bintang Bank',
      accountNumber: '5423325552',
      accountName: 'Trading Account',
      accountType: 'Cash Deposit',
      amount: '1,000,00',
      isDormant: false,
      createdAt: new Date(),
    },
    {
      id: 4,
      userId: 'mv5hm6rWVWeeDQy0EbU7LWR8KFq1',
      bankName: 'Bintang Bank',
      accountNumber: '101022234445',
      accountName: 'Personal Savings-i',
      accountType: 'Savings',
      amount: '5,000,00',
      isDormant: false,
      createdAt: new Date(),
    },
    {
      id: 5,
      userId: 'mv5hm6rWVWeeDQy0EbU7LWR8KFq1',
      bankName: 'Bintang Bank',
      accountNumber: 'CA10133466433',
      accountName: 'Current Account-i',
      accountType: 'Current',
      amount: '15,425,23',
      isDormant: false,
      createdAt: new Date(),
    },
  ],
};
