export enum AppRoutes {
  AccountList = 'AccountList',
  Accounts = 'Accounts',
  CardList = 'CardList',
  ConnectionError = 'ConnectionError',
  CreateDisplayName = 'CreateDisplayName',
  Dashboard = 'Dashboard',
  FixedDeposit = 'FixedDeposit',
  GeneralModal = 'GeneralModal',
  Home = 'Home',
  Loan = 'Loan',
  Login = 'Login',
  Settings = 'Settings',
  SomethingWrong = 'SomethingWrong',
  Startup = 'Startup',
  Wealth = 'Wealth',
}
